version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo-db
    ports:
      - 3306:3306
    command: --sql_mode='' --max_allowed_packet=32505856
